### PR TITLE
Update provider to match the rest of octodns-*

### PR DESCRIPTION
**Pull request by ross**
There are no actual code changes here, just a pass that brings everything in line with how all the other octodns modules are laid out and work. This should allow all the existing tooling/processes to apply cleanly to this provider so that it's not left behind (as it has been up to this point.)

/cc https://github.com/octodns/octodns-fastly/pull/13#issuecomment-1793482632 @istr

### CODE REVIEW

**Comment by ross** [comment]
Will have to look into why 3.8 is failing later, I'm out of time today. Part of the resaon for making this switch to bring things in line is to get all the full testing setup and find stuff like this.

**Comment by istr** [comment]
> Will have to look into why 3.8 is failing later, I'm out of time today. Part of the resaon for making this switch to bring things in line is to get all the full testing setup and find stuff like this.

See https://stackoverflow.com/questions/66846743/importerror-cannot-import-name-cache-from-functools and https://docs.python.org/3/library/functools.html#functools.cache.

I pushed a commit to this branch to change this.

However, it seems that there are some more backwards compatibility issues to be fixed.

**Comment by istr** [comment]
@ross only `removesuffix` needed to be replaced. So we are all set.

I think the `suffix = "." + zone.name[:-1]` is safe, since the zone name is guaranteed to end with a dot.
But you might want to review, just in case.

**Comment by ross** [comment]
> @ross only `removesuffix` needed to be replaced. So we are all set.

Thanks for the fixes!

**Comment by ross** [comment]
Moving forward with this now. Should allow us to keep everything in sync going forward. Again no actual changes to the code/functionality should have been made as part of this. It's just making everything surrounding the code, setup.py, readme, changelog, versioning, ... line up with everything else.

**Pull request merged**
